/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageZoom: typeof import('./components/ImageZoom.vue')['default']
    ListSynthese: typeof import('./components/ListSynthese.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
